# Generated by Django 3.2.1 on 2021-05-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Song',
        ),
    ]
