# Generated by Django 3.2.1 on 2021-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('songs', '0002_rename_post_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='content',
            new_name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='voice',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
